#ifndef TVREMOTECONTROLLER_BUTTON_STATE_H
#define TVREMOTECONTROLLER_BUTTON_STATE_H

enum class ButtonState {
	BUTTON_STATE_NORMAL, BUTTON_STATE_PRESSED, BUTTON_STATE_BACK
};

#endif //TVREMOTECONTROLLER_BUTTON_STATE_H
